# Numpy

## Arrays

In [1]:
import numpy

def arrays(arr):
    return numpy.array(arr[::-1], float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


## Shape and Reshape

In [22]:
import numpy as np
print(np.array(input().split(), int).reshape(3, 3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Transpose and Flatten

In [31]:
import numpy as np
n, m = map(int, input().split())
arr = np.array([input().split() for _ in range(n)], int)
print(arr.transpose(), arr.flatten(), sep="\n")

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


## Concatenate

In [35]:
import numpy as np
m, n, p = map(int, input().split())
arr1 = np.array([input().split() for _ in range(m)], int)
arr2 = np.array([input().split() for _ in range(n)], int)
print(np.concatenate((arr1, arr2), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Zeros and Ones

In [36]:
import numpy as np
d = tuple(map(int, input().split()))
print(np.zeros(d, int))
print(np.ones(d, int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## Eye and Identity

In [37]:
import numpy as np
n, m = map(int, input().split())
print(str(np.eye(n, m, k=0, dtype=float)).replace('1', ' 1').replace('0', ' 0'))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Array Mathematics

In [38]:
import numpy as np

n, m = map(int, input().split())
arr1 = np.array([input().split() for _ in range(n)], int)
arr2 = np.array([input().split() for _ in range(n)], int)

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 // arr2)
print(arr1 % arr2)
print(arr1 ** arr2)


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## Floor, Ceil and Rint

In [42]:
import numpy as np
import re

def resolve_bug(arr):
    return re.sub(r"(\d+)\.", r" \1.", str(arr))

arr = np.array(input().split(), dtype=float)
print(resolve_bug(np.floor(arr, dtype=float))) # Applies the floor function to each element of the array.
print(resolve_bug(np.ceil(arr, dtype=float))) # Applies the ceil function to each element of the array.
print(resolve_bug(np.rint(arr))) #Round each element of the array to the nearest integer.


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## Sum and Prod

In [39]:
import numpy as np
n, m = map(int, input().split())
print(np.prod(np.sum(np.array([input().split() for _ in range(n)], int), axis = 0)))

2 2
1 2
3 4
24


## Min and Max

In [40]:
import numpy as np
n, m = map(int, input().split())
arr = np.array([input().split() for _ in range(n)], int)
print(np.max(np.min(arr, axis=1)))

4 2
2 5
3 7
1 3
4 0
3


## Mean, Var, and Std

In [41]:
import numpy as np
import re

def resolve_bug(arr):
    return re.sub(r"(\d+)\.", r" \1.", str(arr))

n, m = map(int, input().split())
arr = np.array([input().split() for _ in range(n)], int)

print(resolve_bug(np.mean(arr, axis = 1)))
print(resolve_bug(np.var(arr, axis = 0)))
print(round(np.std(arr), 12))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


## Dot and Cross

In [43]:
import numpy as np
n = int(input())
arr1 = np.array([input().split() for _ in range(n)], int)
arr2 = np.array([input().split() for _ in range(n)], int)
print(np.dot(arr1, arr2))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


## Inner and Outer

In [44]:
import numpy as np
arr1 = np.array(input().split(), int)
arr2 = np.array(input().split(), int)
print(np.inner(arr1, arr2))
print(np.outer(arr1, arr2))

0 1
2 3
3
[[0 0]
 [2 3]]


## Polynomials

In [45]:
import numpy as np
arr = np.array(input().split(), float)
x = float(input())
print(np.polyval(arr, x))

1.1 2 3
0
3.0


## Linear Algebra

In [46]:
import numpy as np
n = int(input())
arr = np.array([input().split() for _ in range(n)], float)
print(round(np.linalg.det(arr), 2))

2
1.1 1.1
1.1 1.1
0.0
