# NumPy
<pre>    <b>Numeric Python</b> </pre>

It is a __python package__ that provides the power to handle the large number of operations <br>
 over a __large set of numerical (ndimensional)data in an memory efficient way and very fast__ <br>
Which was earlier not very possible with noramal python's list.

## Advantages
__(Showing were we right about memory efficient / fast execution time)?__

### Memory Efficient

In [132]:
import numpy as np #Standard convention used for importing the numpy package
import sys

np_array = np.array(range(100000))
py_list = list(range(100000))


print(sys.getsizeof(np_array)) #it calls __sizeof__ method to get size of the object in memory and ads garbage collector overhead also (if any)(in bytes).)
print(py_list.__sizeof__()) 

400096
900088


As, it is evident that the numpy array for same range as of normal python list is occupying less than half the size of python list in memory.<br>

### Fast Execution Time

In [133]:
#Suppose we want to multiple by each element by 10
from datetime import *
start_time = datetime.now() #Capturing the start execution time
rs_np_2 = np_array*10
end_time = datetime.now()
print("Time Taken By Numpy : ", (end_time - start_time))

start_time = datetime.now()
rs_py_list_2 = [each*10 for each in py_list]
end_time = datetime.now()
print("Time Taken By PythonList : ", (end_time - start_time))


Time Taken By Numpy :  0:00:00.001003
Time Taken By PythonList :  0:00:00.013670


## Creating Arrays

In [199]:
#Creating an array
arr = np.array([[1,2,3], [3,4,5]]) 

In [200]:
type(arr) # it returns a ndarray object (i.e. ndimensional array)

numpy.ndarray

In [214]:
#As arrays can be of any dimensional 
print(arr.ndim) # This will retur the dimension of the array
print(arr.shape) # Returns the tuple with number of elemnets for each dimension (e.g. for 2-demsional (n,m) n-no of rows, m-no of columns)

1
(4,)


__np.reshape__<br>
We can change the dimension of the array by passing the desired (shaping elements) in the tuple

In [218]:
np.array([1,2,3,4,5,6]).reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

### Built-ins np.zeros, np.ones, np.arange, np.linspace
__NumPy has built-in functions for creating arrays__

__np.zeros__

In [202]:
np.zeros(2)  #Creates arrays of defined shape with all emlements as zeros

array([0., 0.])

__np.ones__

In [203]:
print(np.ones(2))  #Creates arrays of defined shape with all emlements as ones
print(np.ones((3,2)))  #Creating 2 dimensional array of ones

[1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


__np.arange__

In [204]:
# It is very much similar to python range function but this return a ndarray object.
#Signature : np.arange(start, stop, step, dtype)

In [205]:
print(np.arange(10, 20, 2)) #Returning a array starting from 10 to 20 with each time increment of 2

[10 12 14 16 18]


__np.linspace__<br>
__Return evenly spaced numbers over a specified interval.__

In [206]:
# We will start from 1 to 10 and divide then into num-1 parts and returns num be evenly spaced numbers.
np.linspace(1,10,num=6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

## Indexing and Slicing

__Indexing__

In [207]:
arr = np.array([ 10, 20, 30, 40 ])

Like python lists numpy ndarray is also indexed starting from 0.<br>
Single elements can be accessed like

In [208]:
print(arr[0]) #Returns the first element of the array

10


We can also access the the elements with negative index <br>
It's special fetaure that provides it basically indexes its element from -1 starting from the end. <br>
i.e.<br>
<pre>                    [ 10, 20, 30, 40 ]<br>
positive indexing :    0   1   2   3<br>
negative indexing :   -4  -3  -2  -1<br></pre>

In [209]:
print(arr[-1]) # this will return the last element

40


__Slicing__

It is taking a way of taking subpart of the array, similar to slicing in python list.<br>
\[n:m\]  This will return a subpart of the array startting from n to m-1

In [210]:
# arr declared above as [10, 20, 30, 40]
#                        1, 2,  3,  4
#                       -4  -3 -2   -1
arr[2:4] # This will return elements starting from 2 to 3.

array([30, 40])

In [211]:
# Similar, to this we can also make use of negative indexing
arr[-2:] # When we do not specify m it is traversed till the end, and similarly, if we do not specified n it is started from the start

array([30, 40])

In [212]:
# We can also mention the step i.e. the index value that should be added at each step.
# Syntax : arr[n:m:step] 
# for e.g. we want alternate numbers only

arr[::2] # Observe, we do not specified n amd m this means the array will be traversed from start to end with step=2 each increent by 2.

array([10, 30])

In [219]:
# We can traverse the array in reverse by using negative index
arr[::-1] # End to Start Traverse

array([40, 30, 20, 10])

## np.transpose

In [230]:
# Transpose the given array (i.e. Changing the columns to rows)
np.array([[1,2,3,4],[5,6,7,8]]).transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## np.flatten

In [232]:
# flatten the given array (i.e. Merging all rows into a single one)
np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]).flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## np.concatenate
It concatenates two or more arrays together.<br>
It takes an axis an parameter \[axis = 0 (along the rows) axis = 1 (along the columns)\] make sure that on the axis on which u concatenate both the array have same dimension for that axis.

In [246]:
np.concatenate((np.array([[1, 2, 3]]), np.array([[4, 5, 6]])), axis=0)

array([[ 1,  2,  3],
       [-1, -2, -3],
       [ 4,  5,  6],
       [-4, -5, -6]])

## Mathematical Operations

It performs element wise mathematical operations over two given np arrays.

In [272]:
#Let's consider we have two arrays of same shape
#Please make sure that the array's must be of shape otherwise, it will throw an error because mathematic functions are performed element wise.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

#Addition
print(np.add(arr1, arr2)) # This will perform element wise addition of two arrays.
print(arr1 + arr2) # It also provides addition via operator overloading

#Subtraction
print(np.subtract(arr1, arr2)) # This will perform element wise subtraction of two arrays.
print(arr1 - arr2) # It also provides subtraction via operator overloading

#Multiplication
print(np.multiply(arr1, arr2)) # This will perform element wise multiplication of two arrays.
print(arr1 * arr2 ) # It also provides multiplication via operator overloading

#Division
print(np.divide(arr1, arr2)) # This will perform element wise division of two arrays.
print(arr1 / arr2 ) # It also provides division via operator overloading

[5 7 9]
[5 7 9]
[-3 -3 -3]
[-3 -3 -3]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]


## np.floor, np.ceil and np.rint

In [289]:
arr = np.array([1.2, 2.3, 3.4, 4.5, 5.6, 6.7])
print(np.floor(arr, dtype=float)) # Applies the floor function to each element of the array.
print(np.ceil(arr, dtype=float)) # Applies the ceil function to each element of the array.
print(np.rint(arr)) #Round each element of the array to the nearest integer.

[1. 2. 3. 4. 5. 6.]
[2. 3. 4. 5. 6. 7.]
[1. 2. 3. 4. 6. 7.]


## np.sum

In [292]:
#Performs Sum of array elements over a given axis.
arr = np.array([[1, 2, 3], [4, 5, 6]]) #Let's take an 2-dimensional array.
print(np.sum(arr, axis = 0)) # as , we mentioned axis =0 so, this provide the sum along the columns.
print(np.sum(arr, axis = 1)) # as , we mentioned axis =1 so, this provide the sum along the rows.
print(np.sum(arr)) # When we don't mention any array by default it is axis =None and provide sum of all elements.

[5 7 9]
[ 6 15]
21


## np.prod

In [295]:
#Performs product of array elements over a given axis.
arr = np.array([[1, 2, 3], [4, 5, 6]]) #Let's take an 2-dimensional array.
print(np.prod(arr, axis = 0)) # as , we mentioned axis =0 so, this provide the product along the columns.
print(np.prod(arr, axis = 1)) # as , we mentioned axis =1 so, this provide the product along the rows.
print(np.prod(arr)) # When we don't mention any array by default it is axis =None and provide product of all elements.

[ 4 10 18]
[  6 120]
720


In [ ]:
np.vectorize